# Generated by Django 3.2.16 on 2023-01-09 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_logs_generated_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs_json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenght', models.CharField(max_length=255)),
                ('Layer_ETH', models.TextField()),
                ('Layer_IP', models.TextField()),
                ('Layer_UDP', models.TextField()),
                ('Layer_ARP', models.TextField()),
                ('Layer_TCP', models.TextField()),
                ('Layer_TLS', models.TextField()),
                ('Layer_DNS', models.TextField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
